export const BRIDGE_PROTOCOL_VERSION = 1 as const;

export const BridgeMessageType = {
  VIEWER_READY: 'VIEWER_READY',
  ACTIVATE_TOOL: 'ACTIVATE_TOOL',
  DEACTIVATE_TOOL: 'DEACTIVATE_TOOL',
  FOCUS_MEASUREMENT: 'FOCUS_MEASUREMENT',
  DELETE_MEASUREMENT: 'DELETE_MEASUREMENT',
  MEASUREMENT_ADDED: 'MEASUREMENT_ADDED',
  MEASUREMENT_UPDATED: 'MEASUREMENT_UPDATED',
  MEASUREMENT_REMOVED: 'MEASUREMENT_REMOVED',
} as const;

export const ViewerTool = {
  ELLIPTICAL_ROI: 'EllipticalROI',
  LENGTH: 'Length',
} as const;

export type ViewerToolName = (typeof ViewerTool)[keyof typeof ViewerTool];
