export const BRIDGE_PROTOCOL_VERSION = 1 as const;

export const BridgeMessageType = {
  VIEWER_READY: 'VIEWER_READY',
  ACTIVATE_TOOL: 'ACTIVATE_TOOL',
  DEACTIVATE_TOOL: 'DEACTIVATE_TOOL',
  MEASUREMENT_ADDED: 'MEASUREMENT_ADDED',
  MEASUREMENT_UPDATED: 'MEASUREMENT_UPDATED',
} as const;

export const ViewerTool = {
  ELLIPTICAL_ROI: 'EllipticalROI',
} as const;
